### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by jackwilsdon** [blay09/RefinedRelocation2#106]
I'm getting the following error when trying to build this mod (commit 409077d6ce56e1bdd94346f2e3d1ef7c9f255a25) with `gradlew build` on Windows:

```
> Task :compileApiJava
Error getting artifact: mezz.jei:jei-1.15.2:6.0.0.2_mapped_snapshot_20200226-1.15.1:null@pom from  DeobfuscatingRepo
org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':__obfuscated'.
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.getFailure(DefaultLenientConfiguration.java:143)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.rethrowFailure(DefaultLenientConfiguration.java:156)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultResolvedConfiguration.rethrowFailure(DefaultResolvedConfiguration.java:43)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultResolvedConfiguration.getFirstLevelModuleDependencies(DefaultResolvedConfiguration.java:71)
	...bunch more lines here...
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find ignored:ironchest:1.15.2-10.0.3.
Searched in the following locations:
  - https://minecraft.curseforge.com/api/maven/ignored/ironchest/1.15.2-10.0.3/ironchest-1.15.2-10.0.3.pom
  - https://minecraft.curseforge.com/api/maven/ignored/ironchest/1.15.2-10.0.3/ironchest-1.15.2-10.0.3.jar
  - https://dvs1.progwml6.com/files/maven/ignored/ironchest/1.15.2-10.0.3/ironchest-1.15.2-10.0.3.pom
  - https://dvs1.progwml6.com/files/maven/ignored/ironchest/1.15.2-10.0.3/ironchest-1.15.2-10.0.3.jar
  - https://modmaven.k-4u.nl/ignored/ironchest/1.15.2-10.0.3/ironchest-1.15.2-10.0.3.pom
  - https://modmaven.k-4u.nl/ignored/ironchest/1.15.2-10.0.3/ironchest-1.15.2-10.0.3.jar
  - file:/C:/Users/Jack Wilsdon/Documents/Development/RefinedRelocation2/run/obfmods/ironchest-1.15.2-10.0.3.jar
  - file:/C:/Users/Jack Wilsdon/Documents/Development/RefinedRelocation2/run/obfmods/ironchest.jar
Required by:
    project :
	at org.gradle.internal.resolve.result.DefaultBuildableComponentResolveResult.notFound(DefaultBuildableComponentResolveResult.java:39)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:108)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolve(RepositoryChainComponentMetaDataResolver.java:63)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ComponentMetaDataResolverChain.resolve(ComponentResolversChain.java:94)
	...bunch more lines here...
Error getting artifact: mezz.jei:jei-1.15.2:6.0.0.2_mapped_snapshot_20200226-1.15.1:api@jar from  DeobfuscatingRepo
org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':__obfuscated'.
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.getFailure(DefaultLenientConfiguration.java:143)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.rethrowFailure(DefaultLenientConfiguration.java:156)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultResolvedConfiguration.rethrowFailure(DefaultResolvedConfiguration.java:43)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultResolvedConfiguration.getFirstLevelModuleDependencies(DefaultResolvedConfiguration.java:71)
	...bunch more lines here...
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find ignored:ironchest:1.15.2-10.0.3.
Searched in the following locations:
  - https://minecraft.curseforge.com/api/maven/ignored/ironchest/1.15.2-10.0.3/ironchest-1.15.2-10.0.3.pom
  - https://minecraft.curseforge.com/api/maven/ignored/ironchest/1.15.2-10.0.3/ironchest-1.15.2-10.0.3.jar
  - https://dvs1.progwml6.com/files/maven/ignored/ironchest/1.15.2-10.0.3/ironchest-1.15.2-10.0.3.pom
  - https://dvs1.progwml6.com/files/maven/ignored/ironchest/1.15.2-10.0.3/ironchest-1.15.2-10.0.3.jar
  - https://modmaven.k-4u.nl/ignored/ironchest/1.15.2-10.0.3/ironchest-1.15.2-10.0.3.pom
  - https://modmaven.k-4u.nl/ignored/ironchest/1.15.2-10.0.3/ironchest-1.15.2-10.0.3.jar
  - file:/C:/Users/Jack Wilsdon/Documents/Development/RefinedRelocation2/run/obfmods/ironchest-1.15.2-10.0.3.jar
  - file:/C:/Users/Jack Wilsdon/Documents/Development/RefinedRelocation2/run/obfmods/ironchest.jar
Required by:
    project :
	at org.gradle.internal.resolve.result.DefaultBuildableComponentResolveResult.notFound(DefaultBuildableComponentResolveResult.java:39)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:108)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolve(RepositoryChainComponentMetaDataResolver.java:63)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ComponentMetaDataResolverChain.resolve(ComponentResolversChain.java:94)
	...bunch more lines here...
Setting up MCP environment
Initializing steps
Executing steps
 > Running 'downloadManifest'
 > Running 'downloadJson'
 > Running 'downloadClient'
 > Running 'downloadServer'
 > Running 'stripClient'
 > Running 'stripServer'
 > Running 'merge'
 > Running 'rename'
Stopping at requested step: C:\Users\Jack Wilsdon\.gradle\caches\forge_gradle\mcp_repo\de\oceanlabs\mcp\mcp_config\1.15.2-20200307.202953\joined\rename\output.jar
Creating SRG -> MCP TSRG

> Task :compileApiJava FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings
1 actionable task: 1 executed
```
(full log [here](https://gist.github.com/jackwilsdon/9045b8acd30ae424c88d38343b940e70))

Am I doing something wrong here?

**Comment by BlayTheNinth** [comment]
You have to comment out the Iron Chest dependency in the build.gradle, or place the file it's looking for into a folder called "run/obfmods".

**Comment by BlayTheNinth** [comment]
https://github.com/blay09/RefinedRelocation2/commit/973aadffdeba72f5166912d2faf48df8b202607c comments out the dependency since it's not strictly needed for building
