### ISSUE TITLE
Refined Relocation eats bees

### ISSUE THREAD

**Issue by luke-bravenboer** [blay09/RefinedRelocation2#44]
¯\\\_(ツ)_/¯

So I made a super simple sorting network for restocking a forestry Apiary. The output is being pulled out with a (vanilla) hopper below the apiary, sending the items into a Sorting Chest. It's attached to a Sorting Interface, configured to whitelist princesses & drones, facing into the Apiary; as well as a storage Sorting Chest, configured to whitelist all items on low priority.

The moment the queen dies & sends items into the sorting system, the game crashes with the below exception, destroying one of the bees in the process. I've narrowed it right down, and have found that it actually occurs when a Sorting Interface is facing the apiary, regardless of the filters, or even the sorting system at all; in fact, I've reproduced the bug with nothing more than 3 blocks stacked vertically; a Sorting Interface, with no filters set, on top of the apiary, with a vanilla hopper below. The interface shouldn't be connected at all now, but it's still somehow crashing at the same insertIntoSortingGrid() method.

**Stack trace:**
```
java.lang.RuntimeException: Refined Relocation just ate one of your items and that's really weird because this should never happen. Now go and report this so I can have a further look into this.
	at net.blay09.mods.refinedrelocation.InternalMethodsImpl.insertIntoSortingGrid(InternalMethodsImpl.java:146)
	at net.blay09.mods.refinedrelocation.api.RefinedRelocationAPI.insertIntoSortingGrid(RefinedRelocationAPI.java:47)
	at net.blay09.mods.refinedrelocation.grid.SortingInventory.onUpdate(SortingInventory.java:60)
	at net.blay09.mods.refinedrelocation.grid.SortingGridMember.onUpdate(SortingGridMember.java:45)
	at net.blay09.mods.refinedrelocation.tile.TileSortingInterface.update(TileSortingInterface.java:59)
	at net.minecraft.world.World.redirect$tileEntityUpdate$zbf000(World.java:5129)
	at net.minecraft.world.World.updateEntities(World.java:1832)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
```

**Detailed error report:**
https://paste.dimdev.org/bibefulolu.txt

**Versions:**
Refined Relocation 2: 1.12.2-4.2.23
Forestry: 1.12.2-5.8.0.291
Forge: 14.23.3.2675

**Comment by luke-bravenboer** [comment]
Side note, if you break the Sorting Interface while it's attached to any inventory, it drops all of that inventory's contents on the ground... that's not intended, is it?
