### ISSUE TITLE
Sorting Interface broken on dedicated servers?

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/RefinedRelocation2#46]
From CurseForge:
> Has anyone gotten the sorting interface working on a server?  I get an exception in my log when I try to access the sorting interface filter GUI, but only when playing on my server.  If I start a single-player game with the same set of mods, it works fine.  I'm not sure about LAN.  I have not yet entered a bug report, as I cannot 100% rule out conflicts with other mods.

**Comment by gazpachoking** [comment]
Hmm, it's still crashing in multiplayer for me (but working fine in single player.) Using 1.12.2-4.2.28, getting this crash in the server log:
```
java.lang.RuntimeException: Missing
        at net.minecraftforge.fml.server.FMLServerHandler.getClientToServerNetworkManager(FMLServerHandler.java:299)
        at net.minecraftforge.fml.common.FMLCommonHandler.getClientToServerNetworkManager(FMLCommonHandler.java:555)
        at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$10.selectNetworks(FMLOutboundHandler.java:329)
        at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToServer(SimpleNetworkWrapper.java:321)
        at net.blay09.mods.refinedrelocation.InternalMethodsImpl.openRootFilterGui(InternalMethodsImpl.java:238)
        at net.blay09.mods.refinedrelocation.api.RefinedRelocationAPI.openRootFilterGui(RefinedRelocationAPI.java:91)
        at net.blay09.mods.refinedrelocation.block.BlockSortingChest.func_180639_a(BlockSortingChest.java:118)
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449)
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739)
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55)
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11)
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by BlayTheNinth** [comment]
This will be fixed in the next version, until then instead of getting to the filter menu via shift-right-click you can use the filter button in the corner of the GUI.

**Comment by gazpachoking** [comment]
Nice, thanks!

**Comment by gazpachoking** [comment]
Hmm, I upgraded to 4.2.29 and am still having this problem.
```
java.lang.RuntimeException: Missing
        at net.minecraftforge.fml.server.FMLServerHandler.getClientToServerNetworkManager(FMLServerHandler.java:299)
        at net.minecraftforge.fml.common.FMLCommonHandler.getClientToServerNetworkManager(FMLCommonHandler.java:555)
        at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$10.selectNetworks(FMLOutboundHandler.java:329)
        at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToServer(SimpleNetworkWrapper.java:321)
        at net.blay09.mods.refinedrelocation.InternalMethodsImpl.openRootFilterGui(InternalMethodsImpl.java:238)
        at net.blay09.mods.refinedrelocation.api.RefinedRelocationAPI.openRootFilterGui(RefinedRelocationAPI.java:91)
        at T145.metalchests.blocks.BlockSortingMetalChest.func_180639_a(BlockSortingMetalChest.java:92)
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449)
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739)
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55)
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11)
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:745)
```
EDIT: Upon further testing, the exception is only when using sorting MetalChests. When shift-right clicking a plain sorting chest, I don't get an exception, but it just opens the chest, not brings up the filter gui. The problem with MetalChests is that they don't have the button in their own interface to bring up the filtering gui without shift-right clicking. (They work fine in single player though.)

**Comment by BlayTheNinth** [comment]
Didn't realize Metal Chests added Refined Relocation support, I've pushed another fix that should fix it for those chests as well.

**Comment by gazpachoking** [comment]
Thanks! Does this also fix the issue with the vanilla sorting chests just opening with shift-rightclick instead of giving the filtering gui?

**Comment by BlayTheNinth** [comment]
I'm not experiencing that issue, so either it's been fixed or there is more to it.

**Comment by gazpachoking** [comment]
Okay, I'll give another test when Jenkins starts building successfully again.

**Comment by BlayTheNinth** [comment]
Whoops, build is fixed now.

**Comment by gazpachoking** [comment]
Nice. Filter interface is working properly on metal chests now, thanks! I forgot to test the vanilla ones again.
